"""
===============================================================================
KSHETRA: Persistence Layer — Seed Script
===============================================================================

STEP 1 OF THE PERSISTENCE PLAN. Reproduces the existing demo dataset from
src/data/mockData.ts (INITIAL_PROJECT, INITIAL_PARCELS, INITIAL_ALERTS,
INITIAL_ACTIONS, INITIAL_AUDIT_LOGS) into the SQLite database defined by
backend/database.py, for the six approved tables.

Not imported by backend/main.py, not wired to any router. Run directly:

    python seed.py

SAFE TO RUN REPEATEDLY (idempotent upsert):
  - Every record keeps the exact same application ID the frontend already
    uses (e.g. "P-0245", "proj-nh79x", "ALT-1092", "ACT-501", "LOG-901").
  - For each record: if a row with that ID already exists, its fields are
    overwritten in place (upsert-by-natural-key); if not, it is inserted.
    No duplicate rows are ever created by re-running this script.
  - The `predictions` table is intentionally NOT seeded: ProjectPrediction
    records don't exist as static mock data anywhere in the frontend (they
    are generated at runtime by calling /predict), so there is nothing to
    reproduce. The table is created empty and stays empty until a future
    persistence-aware prediction endpoint (Step 3+) writes to it.

This data is a straight transcription of src/data/mockData.ts — no field is
invented or altered. src/data/mockData.ts itself is NOT imported (it's a
TypeScript module); the values below are hand-copied from it and may drift
if mockData.ts changes. That drift risk is called out in the Step 1 report's
"compatibility concerns" section.
"""

from __future__ import annotations

from typing import Any, Dict, List

from database import Base, SessionLocal, engine
from models import Alert, AuditLog, CaseAction, Parcel, Project

PROJECT_ID = "proj-nh79x"
PROJECT_NAME = "Salem-Chennai Express Highway Corridor (NH-79X)"


# -----------------------------------------------------------------------------
# 1 project — mirrors src/data/mockData.ts INITIAL_PROJECT
# -----------------------------------------------------------------------------
PROJECTS: List[Dict[str, Any]] = [
    {
        "id": PROJECT_ID,
        "name": PROJECT_NAME,
        "code": "NHAI-TN-2024-EXP-08",
        "department": "Ministry of Road Transport & Highways (MoRTH)",
        "agency": "NHAI",
        "total_length_km": 68.4,
        "project_value_crores": 4620,
        "total_parcels": 380,
        "acquired_parcels": 242,
        "pending_parcels": 138,
        "high_risk_parcels": 28,
        "med_risk_parcels": 46,
        "low_risk_parcels": 64,
        "predicted_delay_months": 4.2,
        "status": "At Risk",
        "current_larr_stage": "Award Inquiry (Sec 3G/23)",
        "corridor_sections": [
            {
                "sectionId": "sec-1",
                "name": "Section 1: Kandhampatty Bypass to Omalur Jct",
                "chainageKm": "Km 0.0 - 18.2",
                "riskScore": 24,
                "riskLevel": "low",
                "bottleneckCount": 2,
                "description": "92% land acquisition complete. Clear title distribution across industrial belts.",
            },
            {
                "sectionId": "sec-2",
                "name": "Section 2: Omalur to Kamalapuram & Airport Link",
                "chainageKm": "Km 18.2 - 42.5",
                "riskScore": 84,
                "riskLevel": "high",
                "bottleneckCount": 19,
                "description": "Critical bottleneck area: Multiple civil stay orders (OS 412/2023) and fragmented co-heir mutation backlogs.",
            },
            {
                "sectionId": "sec-3",
                "name": "Section 3: Kamalapuram to Thoppur Ghats",
                "chainageKm": "Km 42.5 - 68.4",
                "riskScore": 52,
                "riskLevel": "medium",
                "bottleneckCount": 7,
                "description": "Moderate delay risk. Forest department clearance pending for 3 reserve forest boundary parcels.",
            },
        ],
        "corridor_path": [
            [11.6643, 78.1460],
            [11.6850, 78.1250],
            [11.7230, 78.0820],
            [11.7580, 78.0460],
            [11.7920, 78.0120],
            [11.8350, 77.9850],
        ],
        "start_point_name": "Salem Bypass (Kandhampatty)",
        "end_point_name": "Thoppur Ghats Link",
        "start_lat": 11.6643,
        "start_lng": 78.1460,
        "end_lat": 11.8350,
        "end_lng": 77.9850,
        "is_custom_project": False,
        "project_type": None,
        "planning_priorities": None,
    }
]


# -----------------------------------------------------------------------------
# 8 parcels — mirrors src/data/mockData.ts INITIAL_PARCELS
# -----------------------------------------------------------------------------
PARCELS: List[Dict[str, Any]] = [
    {
        "id": "P-0245",
        "survey_number": "125/2",
        "ulpin": "TN-SLM-2024-88412",
        "project_id": PROJECT_ID,
        "project_name": PROJECT_NAME,
        "owner_name": "Thiru. R. Ramasamy & 4 Co-sharers",
        "co_owners": ["R. Ramasamy", "R. Muthuvel", "Smt. Saraswathi", "K. Palanisamy", "R. Loganathan"],
        "co_owner_count": 5,
        "village": "Kamalapuram",
        "taluk": "Omalur",
        "district": "Salem",
        "area_acres": 2.40,
        "area_sq_meters": 9712,
        "mutation_status": "Disputed",
        "last_mutation_years_ago": 14,
        "document_status": "Disputed",
        "record_freshness_score": 38,
        "record_confidence": "Low",
        "court_case": True,
        "court_case_status": "Active - Stay Order",
        "ownership_dispute": "Yes - Partition Suit",
        "court_record": {
            "caseNumber": "O.S. 412 / 2023",
            "cnrNumber": "TNSL010045232023",
            "courtName": "Subordinate Court, Omalur",
            "caseType": "Original Civil Suit (Partition & Injunction)",
            "filingDate": "14-Aug-2023",
            "petitioner": "Smt. Saraswathi & Another",
            "respondent": "Thiru. R. Ramasamy & CALA / DRO Salem",
            "caseStatus": "Active - Stay Order",
            "nextHearingDate": "12-Oct-2026",
            "prayer": "Suit for partition of 1/5th ancestral share and interim stay on CALA possession notice under Sec 3E.",
            "interimInjunction": True,
        },
        "revenue_record": {
            "khataNumber": "KH-8841",
            "pattaNumber": "PATTA-904",
            "landClassification": "Wetland (Nanjai)",
            "guidelineValuePerAcre": 4800000,
            "encumbranceStatus": "Pending Partition",
            "lastJamabandiDate": "14-Jul-2018",
            "subRegistrarOffice": "SRO Omalur (Reg. Dist. Salem)",
        },
        "gis_record": {
            "elevationMeters": 284.2,
            "distanceToCorridorCenterMeters": 14.5,
            "intersectionAreaSqM": 9712,
            "environmentalZone": "Buffer Zone",
            "waterBodyAdjacent": True,
            "satelliteImageDate": "18-Jan-2026",
        },
        "acquisition_status": "Pending",
        "stage": "Award Inquiry (Sec 3G/23)",
        "notification_date": "12-Jan-2024",
        "compensation_status": "Pending",
        "estimated_compensation_crores": 1.85,
        "possession_status": "Pending",
        "delay_risk_score": 82,
        "risk_level": "high",
        "predicted_delay_months": 3.8,
        "predicted_delay_range": "3–5 Months",
        "delay_confidence": "High",
        "top_risk_factor": "Active Court Stay Order (O.S. 412/2023) + 5-Way Partition Dispute",
        "ai_explanation": "Parcel P-0245 faces an 82% acquisition delay probability primarily triggered by a civil court stay order on possession, exacerbated by unmutated joint heir succession dating back 14 years and pending compensation deposit in the LA-RA Authority.",
        "shap_factors": [
            {
                "factor": "Civil Court Stay Order on Possession (O.S. 412/2023)",
                "impactPercent": 34,
                "category": "legal",
                "description": "Interim injunction granted by Sub-Court Omalur halting Section 3E eviction.",
                "severity": "HIGH",
            },
            {
                "factor": "Joint Heir Partition Dispute (5 Co-sharers)",
                "impactPercent": 22,
                "category": "ownership",
                "description": "Title unmutated since 2012; two legal heirs residing out of state have not executed consent.",
                "severity": "HIGH",
            },
            {
                "factor": "Compensation Determination Disagreement",
                "impactPercent": 16,
                "category": "compensation",
                "description": "Claimants demanding 2.5x multiplier on commercial guideline value.",
                "severity": "MEDIUM",
            },
            {
                "factor": "Field Survey Extent Discrepancy",
                "impactPercent": 10,
                "category": "spatial",
                "description": "Revenue record shows 2.40 acres while DGPS cadastral drone survey mapped 2.28 acres.",
                "severity": "MEDIUM",
            },
        ],
        "risk_factors_list": [
            "Court case pending (O.S. 412/2023 - Sub-Court Omalur)",
            "5-Way unmutated ancestral partition suit",
            "Compensation dispute with CALA valuation",
            "Document verification pending co-heir affidavits",
        ],
        "recommended_action": "Initiate early legal verification with Government Pleader & refer compensation to LA-RA Authority under Sec 3H(4) to vacate stay.",
        "priority": "CRITICAL",
        "predicted_delay_after_intervention": 1.1,
        "potential_reduction_months": 2.7,
        "intervention_status": "Pending",
        "assigned_officer": "Thiru. M. Senthil Kumar, DRO",
        "assigned_due_date": "28-Aug-2026",
        "field_verified": False,
        "gps_lat": 11.7584,
        "gps_lng": 78.0462,
        "map_coordinates": [
            [11.7578, 78.0452],
            [11.7592, 78.0456],
            [11.7590, 78.0474],
            [11.7576, 78.0468],
        ],
        "center_lat": 11.7584,
        "center_lng": 78.0462,
        "sync_status": "Synced",
        "last_synced_at": "2026-08-23 20:45",
    },
    {
        "id": "P-0189",
        "survey_number": "118/4B",
        "ulpin": "TN-SLM-2024-88350",
        "project_id": PROJECT_ID,
        "project_name": PROJECT_NAME,
        "owner_name": "Smt. Kannammal & K. Subramani",
        "co_owners": ["Smt. Kannammal", "K. Subramani"],
        "co_owner_count": 2,
        "village": "Kamalapuram",
        "taluk": "Omalur",
        "district": "Salem",
        "area_acres": 1.65,
        "area_sq_meters": 6677,
        "mutation_status": "Pending Verification",
        "last_mutation_years_ago": 8,
        "document_status": "Pending Verification",
        "record_freshness_score": 62,
        "record_confidence": "Medium",
        "court_case": False,
        "court_case_status": "None",
        "ownership_dispute": "No",
        "court_record": None,
        "revenue_record": {
            "khataNumber": "KH-8120",
            "pattaNumber": "PATTA-755",
            "landClassification": "Dryland (Punjai)",
            "guidelineValuePerAcre": 3600000,
            "encumbranceStatus": "Clear",
            "lastJamabandiDate": "10-May-2022",
            "subRegistrarOffice": "SRO Omalur",
        },
        "gis_record": {
            "elevationMeters": 278.6,
            "distanceToCorridorCenterMeters": 21.0,
            "intersectionAreaSqM": 5675,
            "environmentalZone": "None",
            "waterBodyAdjacent": False,
            "satelliteImageDate": "05-Feb-2026",
        },
        "acquisition_status": "In-Progress",
        "stage": "Award Inquiry (Sec 3G/23)",
        "notification_date": "15-Feb-2024",
        "compensation_status": "Determined",
        "estimated_compensation_crores": 0.98,
        "possession_status": "Pending",
        "delay_risk_score": 48,
        "risk_level": "medium",
        "predicted_delay_months": 1.8,
        "predicted_delay_range": "1–2 Months",
        "delay_confidence": "High",
        "top_risk_factor": "Joint ownership death certificate verification lag",
        "ai_explanation": "Moderate delay risk due to pending legal heir certificate submission following primary owner demise in 2023.",
        "shap_factors": [
            {
                "factor": "Legal Heirship Certificate Delay",
                "impactPercent": 28,
                "category": "mutation",
                "description": "Tahsildar verification pending for second-generation heirs.",
                "severity": "MEDIUM",
            },
            {
                "factor": "Award Notice Service",
                "impactPercent": 20,
                "category": "document",
                "description": "One co-owner relocated to Coimbatore.",
                "severity": "LOW",
            },
        ],
        "risk_factors_list": [
            "Legal heir certificate verification pending",
            "Co-owner outstation residence",
        ],
        "recommended_action": "Deploy Special Tahsildar for on-site death certificate endorsement and direct bank mandate collection.",
        "priority": "MEDIUM",
        "predicted_delay_after_intervention": 0.4,
        "potential_reduction_months": 1.4,
        "intervention_status": "Assigned",
        "assigned_officer": "Spl. Tahsildar (LA) Unit-2",
        "assigned_due_date": "05-Sep-2026",
        "field_verified": True,
        "gps_lat": 11.7540,
        "gps_lng": 78.0510,
        "map_coordinates": [
            [11.7535, 78.0502],
            [11.7548, 78.0505],
            [11.7545, 78.0520],
            [11.7532, 78.0515],
        ],
        "center_lat": 11.7540,
        "center_lng": 78.0510,
        "sync_status": "Synced",
        "last_synced_at": "2026-08-23 19:30",
    },
    {
        "id": "P-0084",
        "survey_number": "44/1A",
        "ulpin": "TN-SLM-2024-88102",
        "project_id": PROJECT_ID,
        "project_name": PROJECT_NAME,
        "owner_name": "Thiru. N. Dharmalingam",
        "co_owners": ["N. Dharmalingam"],
        "co_owner_count": 1,
        "village": "Kandhampatty",
        "taluk": "Salem West",
        "district": "Salem",
        "area_acres": 3.10,
        "area_sq_meters": 12545,
        "mutation_status": "Up-to-date",
        "last_mutation_years_ago": 2,
        "document_status": "Verified",
        "record_freshness_score": 96,
        "record_confidence": "High",
        "court_case": False,
        "court_case_status": "None",
        "ownership_dispute": "No",
        "court_record": None,
        "revenue_record": {
            "khataNumber": "KH-4410",
            "pattaNumber": "PATTA-312",
            "landClassification": "Dryland (Punjai)",
            "guidelineValuePerAcre": 5200000,
            "encumbranceStatus": "Clear",
            "lastJamabandiDate": "22-Jun-2025",
            "subRegistrarOffice": "SRO Salem West",
        },
        "gis_record": {
            "elevationMeters": 264.8,
            "distanceToCorridorCenterMeters": 30.5,
            "intersectionAreaSqM": 10663,
            "environmentalZone": "None",
            "waterBodyAdjacent": False,
            "satelliteImageDate": "05-Feb-2026",
        },
        "acquisition_status": "Acquired",
        "stage": "Possession (Sec 3E/38)",
        "notification_date": "02-Dec-2023",
        "compensation_status": "Disbursed 100%",
        "estimated_compensation_crores": 2.45,
        "possession_status": "Complete",
        "delay_risk_score": 12,
        "risk_level": "low",
        "predicted_delay_months": 0.2,
        "predicted_delay_range": "0–1 Month",
        "delay_confidence": "High",
        "top_risk_factor": "Clear title & consent agreement signed",
        "ai_explanation": "Low risk. Full award disbursed via RTGS and physical possession handover completed with NHAI contractors.",
        "shap_factors": [
            {
                "factor": "Single undisputed owner with e-Patta",
                "impactPercent": -35,
                "category": "ownership",
                "description": "Complete title clarity with digitized e-Adangal verification.",
                "severity": "LOW",
            },
        ],
        "risk_factors_list": ["No active bottlenecks"],
        "recommended_action": "Proceed with boundary pillar geo-tagging and right-of-way earthwork.",
        "priority": "LOW",
        "predicted_delay_after_intervention": 0.0,
        "potential_reduction_months": 0.2,
        "intervention_status": "Completed",
        "assigned_officer": "Site Engineer, NHAI PIU",
        "assigned_due_date": None,
        "field_verified": True,
        "gps_lat": 11.6720,
        "gps_lng": 78.1380,
        "map_coordinates": [
            [11.6710, 78.1370],
            [11.6730, 78.1375],
            [11.6728, 78.1395],
            [11.6708, 78.1388],
        ],
        "center_lat": 11.6720,
        "center_lng": 78.1380,
        "sync_status": "Synced",
        "last_synced_at": "2026-08-23 18:10",
    },
    {
        "id": "P-0312",
        "survey_number": "204/1",
        "ulpin": "TN-SLM-2024-88590",
        "project_id": PROJECT_ID,
        "project_name": PROJECT_NAME,
        "owner_name": "Thiru. Velusamy & Temple Trust",
        "co_owners": ["Thiru. Velusamy", "Sri Mariamman Temple Hereditary Trustee"],
        "co_owner_count": 2,
        "village": "Omalur",
        "taluk": "Omalur",
        "district": "Salem",
        "area_acres": 1.80,
        "area_sq_meters": 7284,
        "mutation_status": "Disputed",
        "last_mutation_years_ago": 19,
        "document_status": "Disputed",
        "record_freshness_score": 42,
        "record_confidence": "Low",
        "court_case": True,
        "court_case_status": "Pending Hearing",
        "ownership_dispute": "Yes - Joint Heir Conflict",
        "court_record": {
            "caseNumber": "W.P. 18920 / 2024",
            "cnrNumber": "TNMHC01089202024",
            "courtName": "High Court of Madras",
            "caseType": "Writ Petition (HR&CE Land Claim)",
            "filingDate": "10-Feb-2024",
            "petitioner": "HR&CE Department & Temple Trustee",
            "respondent": "CALA / DRO Salem & Thiru. Velusamy",
            "caseStatus": "Pending Hearing",
            "nextHearingDate": "18-Sep-2026",
            "prayer": "Challenge against private patta issuance on Inam temple endowment land.",
            "interimInjunction": False,
        },
        "revenue_record": {
            "khataNumber": "KH-2041",
            "pattaNumber": "PATTA-204 (contested)",
            "landClassification": "Dryland (Punjai)",
            "guidelineValuePerAcre": 4100000,
            "encumbranceStatus": "Encumbered",
            "lastJamabandiDate": "15-Mar-2007",
            "subRegistrarOffice": "SRO Omalur",
        },
        "gis_record": {
            "elevationMeters": 271.4,
            "distanceToCorridorCenterMeters": 12.5,
            "intersectionAreaSqM": 6191,
            "environmentalZone": "None",
            "waterBodyAdjacent": False,
            "satelliteImageDate": "05-Feb-2026",
        },
        "acquisition_status": "Contested",
        "stage": "SIA & Objection (Sec 3C/15)",
        "notification_date": "10-Jan-2024",
        "compensation_status": "Under Dispute in LA-RA Authority",
        "estimated_compensation_crores": 1.62,
        "possession_status": "Pending",
        "delay_risk_score": 78,
        "risk_level": "high",
        "predicted_delay_months": 4.5,
        "predicted_delay_range": "4–6 Months",
        "delay_confidence": "High",
        "top_risk_factor": "HR&CE Religious Endowment Inam Claim",
        "ai_explanation": "High risk of litigation stall due to conflicting historical Inam tenure records between private cultivators and HR&CE Temple Department.",
        "shap_factors": [
            {
                "factor": "HR&CE vs Private Inam Dispute",
                "impactPercent": 38,
                "category": "legal",
                "description": "Madras HC Writ Petition seeking quashing of Section 3A notification.",
                "severity": "HIGH",
            },
            {
                "factor": "Guideline Value Valuation Conflict",
                "impactPercent": 22,
                "category": "compensation",
                "description": "Temple board demanding commercial rate for endowment corpus.",
                "severity": "HIGH",
            },
        ],
        "risk_factors_list": [
            "High Court Writ Petition W.P. 18920/2024",
            "HR&CE religious trust endowment conflict",
            "Inam tenure record ambiguity",
        ],
        "recommended_action": "Convene joint district-level coordination meeting with HR&CE Commissioner and Special Govt Pleader for deposit under Sec 3H.",
        "priority": "HIGH",
        "predicted_delay_after_intervention": 1.8,
        "potential_reduction_months": 2.7,
        "intervention_status": "Assigned",
        "assigned_officer": "District Collector (Special Hearing)",
        "assigned_due_date": "10-Sep-2026",
        "field_verified": False,
        "gps_lat": 11.7340,
        "gps_lng": 78.0720,
        "map_coordinates": [
            [11.7330, 78.0710],
            [11.7350, 78.0715],
            [11.7348, 78.0735],
            [11.7328, 78.0728],
        ],
        "center_lat": 11.7340,
        "center_lng": 78.0720,
        "sync_status": "Synced",
        "last_synced_at": "2026-08-23 20:00",
    },
    {
        "id": "P-0421",
        "survey_number": "89/2B",
        "ulpin": "TN-SLM-2024-88615",
        "project_id": PROJECT_ID,
        "project_name": PROJECT_NAME,
        "owner_name": "Thiru. M. Soundararajan & Sons",
        "co_owners": ["M. Soundararajan", "S. Vignesh", "S. Dinesh"],
        "co_owner_count": 3,
        "village": "Tharamangalam",
        "taluk": "Omalur",
        "district": "Salem",
        "area_acres": 4.20,
        "area_sq_meters": 16996,
        "mutation_status": "Up-to-date",
        "last_mutation_years_ago": 3,
        "document_status": "Verified",
        "record_freshness_score": 88,
        "record_confidence": "High",
        "court_case": False,
        "court_case_status": "None",
        "ownership_dispute": "No",
        "court_record": None,
        "revenue_record": {
            "khataNumber": "KH-0892",
            "pattaNumber": "PATTA-89-2B",
            "landClassification": "Dryland (Punjai)",
            "guidelineValuePerAcre": 3900000,
            "encumbranceStatus": "Clear",
            "lastJamabandiDate": "10-Jun-2023",
            "subRegistrarOffice": "SRO Omalur",
        },
        "gis_record": {
            "elevationMeters": 281.2,
            "distanceToCorridorCenterMeters": 26.0,
            "intersectionAreaSqM": 14447,
            "environmentalZone": "None",
            "waterBodyAdjacent": False,
            "satelliteImageDate": "05-Feb-2026",
        },
        "acquisition_status": "In-Progress",
        "stage": "Compensation Disbursement",
        "notification_date": "05-Jan-2024",
        "compensation_status": "Disbursed 40%",
        "estimated_compensation_crores": 3.10,
        "possession_status": "Partial",
        "delay_risk_score": 28,
        "risk_level": "low",
        "predicted_delay_months": 0.8,
        "predicted_delay_range": "0–1 Month",
        "delay_confidence": "High",
        "top_risk_factor": "Final 60% tranche disbursement scheduled",
        "ai_explanation": "Low risk. Consent agreement signed. Balance 60% compensation awaiting state treasury batch clearance.",
        "shap_factors": [
            {
                "factor": "Treasury voucher queueing",
                "impactPercent": 18,
                "category": "compensation",
                "description": "Standard treasury IFHRMS batch processing window.",
                "severity": "LOW",
            },
        ],
        "risk_factors_list": ["Treasury payment clearance pending"],
        "recommended_action": "Fast-track IFHRMS treasury token clearance with District Treasury Officer.",
        "priority": "LOW",
        "predicted_delay_after_intervention": 0.2,
        "potential_reduction_months": 0.6,
        "intervention_status": "In Progress",
        "assigned_officer": "Accounts Officer, CALA Wing",
        "assigned_due_date": "30-Aug-2026",
        "field_verified": True,
        "gps_lat": 11.7820,
        "gps_lng": 78.0210,
        "map_coordinates": [
            [11.7810, 78.0200],
            [11.7832, 78.0205],
            [11.7828, 78.0225],
            [11.7805, 78.0218],
        ],
        "center_lat": 11.7820,
        "center_lng": 78.0210,
        "sync_status": "Synced",
        "last_synced_at": "2026-08-23 20:30",
    },
    {
        "id": "P-0556",
        "survey_number": "310/2A",
        "ulpin": "TN-SLM-2024-88740",
        "project_id": PROJECT_ID,
        "project_name": PROJECT_NAME,
        "owner_name": "Thiru. Chinnasamy Gounder & 6 Heirs",
        "co_owners": [
            "Chinnasamy Gounder",
            "C. Perumal",
            "C. Murugesan",
            "Smt. Pavalakkodi",
            "C. Natarajan",
            "Smt. Selvi",
            "K. Balan",
        ],
        "co_owner_count": 7,
        "village": "Kamalapuram",
        "taluk": "Omalur",
        "district": "Salem",
        "area_acres": 5.60,
        "area_sq_meters": 22662,
        "mutation_status": "Stale",
        "last_mutation_years_ago": 22,
        "document_status": "Missing Documents",
        "record_freshness_score": 28,
        "record_confidence": "Low",
        "court_case": True,
        "court_case_status": "Pending Hearing",
        "ownership_dispute": "Yes - Partition Suit",
        "court_record": {
            "caseNumber": "O.S. 88 / 2024",
            "cnrNumber": "TNSL010008822024",
            "courtName": "District Munsif Court, Omalur",
            "caseType": "Civil Suit (Title Declaration & Partition)",
            "filingDate": "20-Mar-2024",
            "petitioner": "Smt. Pavalakkodi & Another",
            "respondent": "Thiru. C. Perumal & 5 Others",
            "caseStatus": "Pending Hearing",
            "nextHearingDate": "25-Sep-2026",
            "prayer": "Suit for declaration of share under Hindu Succession Amendment Act 2005.",
            "interimInjunction": False,
        },
        "revenue_record": {
            "khataNumber": "KH-3102",
            "pattaNumber": "PATTA-310-2A",
            "landClassification": "Dryland (Punjai)",
            "guidelineValuePerAcre": 4500000,
            "encumbranceStatus": "Pending Partition",
            "lastJamabandiDate": "12-Aug-2004",
            "subRegistrarOffice": "SRO Omalur",
        },
        "gis_record": {
            "elevationMeters": 276.3,
            "distanceToCorridorCenterMeters": 16.0,
            "intersectionAreaSqM": 19263,
            "environmentalZone": "None",
            "waterBodyAdjacent": False,
            "satelliteImageDate": "05-Feb-2026",
        },
        "acquisition_status": "Pending",
        "stage": "Declaration (Sec 3D/19)",
        "notification_date": "18-Jan-2024",
        "compensation_status": "Pending",
        "estimated_compensation_crores": 4.25,
        "possession_status": "Not Started",
        "delay_risk_score": 89,
        "risk_level": "high",
        "predicted_delay_months": 5.2,
        "predicted_delay_range": "4–6 Months",
        "delay_confidence": "High",
        "top_risk_factor": "7-Way Stale Succession Dispute & Missing Registered Partition Deed",
        "ai_explanation": "Severe delay risk. Land records have not been mutated since 2002. Seven competing legal heirs with an active title suit pending at Munsif Court.",
        "shap_factors": [
            {
                "factor": "Stale Mutation (>20 years)",
                "impactPercent": 36,
                "category": "mutation",
                "description": "Original title holder deceased; revenue records still list pre-partition survey numbers.",
                "severity": "HIGH",
            },
            {
                "factor": "Multi-party Succession Litigation",
                "impactPercent": 30,
                "category": "legal",
                "description": "Gender-equal inheritance claim under 2005 Act disputed by sons.",
                "severity": "HIGH",
            },
            {
                "factor": "Missing Link Documents",
                "impactPercent": 18,
                "category": "document",
                "description": "Original 1974 settlement deed untraceable in Omalur Sub-Registrar archives.",
                "severity": "MEDIUM",
            },
        ],
        "risk_factors_list": [
            "Unmutated revenue records (22 years old)",
            "7 competing legal heirs in active litigation",
            "Missing registered parent settlement documents",
            "No consent agreement on valuation",
        ],
        "recommended_action": "Organize Special Legal Aid Lok Adalat camp at Omalur Taluk office for consensual compensation division under Section 3H(4).",
        "priority": "CRITICAL",
        "predicted_delay_after_intervention": 1.5,
        "potential_reduction_months": 3.7,
        "intervention_status": "Pending",
        "assigned_officer": "Thiru. M. Senthil Kumar, DRO",
        "assigned_due_date": "02-Sep-2026",
        "field_verified": False,
        "gps_lat": 11.7650,
        "gps_lng": 78.0380,
        "map_coordinates": [
            [11.7638, 78.0370],
            [11.7665, 78.0375],
            [11.7660, 78.0398],
            [11.7635, 78.0390],
        ],
        "center_lat": 11.7650,
        "center_lng": 78.0380,
        "sync_status": "Pending",
        "last_synced_at": "2026-08-23 16:00",
    },
    {
        "id": "P-0610",
        "survey_number": "104/1",
        "ulpin": "TN-SLM-2024-88805",
        "project_id": PROJECT_ID,
        "project_name": PROJECT_NAME,
        "owner_name": "M/s Salem Granites Pvt Ltd",
        "co_owners": ["Managing Director, Salem Granites"],
        "co_owner_count": 1,
        "village": "Thoppur",
        "taluk": "Attur",
        "district": "Salem",
        "area_acres": 6.80,
        "area_sq_meters": 27518,
        "mutation_status": "Up-to-date",
        "last_mutation_years_ago": 4,
        "document_status": "Verified",
        "record_freshness_score": 92,
        "record_confidence": "High",
        "court_case": False,
        "court_case_status": "None",
        "ownership_dispute": "No",
        "court_record": None,
        "revenue_record": {
            "khataNumber": "KH-1041",
            "pattaNumber": "PATTA-104-1",
            "landClassification": "Commercial",
            "guidelineValuePerAcre": 6800000,
            "encumbranceStatus": "Clear",
            "lastJamabandiDate": "18-Apr-2022",
            "subRegistrarOffice": "SRO Attur",
        },
        "gis_record": {
            "elevationMeters": 338.5,
            "distanceToCorridorCenterMeters": 20.0,
            "intersectionAreaSqM": 23390,
            "environmentalZone": "None",
            "waterBodyAdjacent": False,
            "satelliteImageDate": "05-Feb-2026",
        },
        "acquisition_status": "In-Progress",
        "stage": "Award Inquiry (Sec 3G/23)",
        "notification_date": "28-Jan-2024",
        "compensation_status": "Determined",
        "estimated_compensation_crores": 5.80,
        "possession_status": "Pending",
        "delay_risk_score": 35,
        "risk_level": "low",
        "predicted_delay_months": 0.9,
        "predicted_delay_range": "0–1 Month",
        "delay_confidence": "High",
        "top_risk_factor": "Mining quarry machinery relocation logistics",
        "ai_explanation": "Low legal delay risk. Minor mechanical delay expected for heavy crushing equipment relocation before site handover.",
        "shap_factors": [
            {
                "factor": "Commercial structure demolition & shifting",
                "impactPercent": 24,
                "category": "spatial",
                "description": "Valuation of industrial shed and transformer dismantling.",
                "severity": "LOW",
            },
        ],
        "risk_factors_list": ["Industrial machinery shifting required"],
        "recommended_action": "Coordinate with PWD Buildings & TANGEDCO for fast-tracked electrical dismantling approval.",
        "priority": "LOW",
        "predicted_delay_after_intervention": 0.3,
        "potential_reduction_months": 0.6,
        "intervention_status": "Assigned",
        "assigned_officer": "Assistant Executive Engineer, NHAI",
        "assigned_due_date": "15-Sep-2026",
        "field_verified": True,
        "gps_lat": 11.8250,
        "gps_lng": 77.9920,
        "map_coordinates": [
            [11.8235, 77.9905],
            [11.8268, 77.9912],
            [11.8260, 77.9940],
            [11.8230, 77.9930],
        ],
        "center_lat": 11.8250,
        "center_lng": 77.9920,
        "sync_status": "Synced",
        "last_synced_at": "2026-08-23 17:45",
    },
    {
        "id": "P-0733",
        "survey_number": "56/3",
        "ulpin": "TN-SLM-2024-88910",
        "project_id": PROJECT_ID,
        "project_name": PROJECT_NAME,
        "owner_name": "Thiru. A. Krishnan & 2 Co-sharers",
        "co_owners": ["A. Krishnan", "A. Soundar", "Smt. Lakshmi"],
        "co_owner_count": 3,
        "village": "Kamalapuram",
        "taluk": "Omalur",
        "district": "Salem",
        "area_acres": 2.15,
        "area_sq_meters": 8700,
        "mutation_status": "Pending Verification",
        "last_mutation_years_ago": 6,
        "document_status": "Pending Verification",
        "record_freshness_score": 58,
        "record_confidence": "Medium",
        "court_case": False,
        "court_case_status": "None",
        "ownership_dispute": "No",
        "court_record": None,
        "revenue_record": {
            "khataNumber": "KH-0563",
            "pattaNumber": "PATTA-56-3",
            "landClassification": "Dryland (Punjai)",
            "guidelineValuePerAcre": 3700000,
            "encumbranceStatus": "Clear",
            "lastJamabandiDate": "05-Jul-2020",
            "subRegistrarOffice": "SRO Omalur",
        },
        "gis_record": {
            "elevationMeters": 279.1,
            "distanceToCorridorCenterMeters": 24.0,
            "intersectionAreaSqM": 7395,
            "environmentalZone": "None",
            "waterBodyAdjacent": False,
            "satelliteImageDate": "05-Feb-2026",
        },
        "acquisition_status": "Pending",
        "stage": "Declaration (Sec 3D/19)",
        "notification_date": "10-Feb-2024",
        "compensation_status": "Pending",
        "estimated_compensation_crores": 1.45,
        "possession_status": "Not Started",
        "delay_risk_score": 54,
        "risk_level": "medium",
        "predicted_delay_months": 2.2,
        "predicted_delay_range": "2–3 Months",
        "delay_confidence": "Medium",
        "top_risk_factor": "Missing co-owner power of attorney documentation",
        "ai_explanation": "Medium delay risk. One co-owner resides abroad in Singapore and power of attorney apostille verification is pending.",
        "shap_factors": [
            {
                "factor": "NRI Power of Attorney Attestation",
                "impactPercent": 26,
                "category": "document",
                "description": "Embassy consular apostille pending for joint bank account mandate.",
                "severity": "MEDIUM",
            },
        ],
        "risk_factors_list": ["Overseas POA attestation in progress"],
        "recommended_action": "Direct CALA legal desk to facilitate digital video conferencing consent affidavit.",
        "priority": "MEDIUM",
        "predicted_delay_after_intervention": 0.8,
        "potential_reduction_months": 1.4,
        "intervention_status": "Pending",
        "assigned_officer": "Legal Assistant, CALA Office",
        "assigned_due_date": "20-Sep-2026",
        "field_verified": False,
        "gps_lat": 11.7500,
        "gps_lng": 78.0560,
        "map_coordinates": [
            [11.7490, 78.0550],
            [11.7512, 78.0555],
            [11.7508, 78.0572],
            [11.7488, 78.0565],
        ],
        "center_lat": 11.7500,
        "center_lng": 78.0560,
        "sync_status": "Synced",
        "last_synced_at": "2026-08-23 18:20",
    },
]


# -----------------------------------------------------------------------------
# 4 alerts — mirrors src/data/mockData.ts INITIAL_ALERTS
# -----------------------------------------------------------------------------
ALERTS: List[Dict[str, Any]] = [
    {
        "id": "ALT-1092",
        "level": "CRITICAL",
        "title": "HIGH RISK ACQUISITION DELAY: Parcel P-0245",
        "project_name": PROJECT_NAME,
        "project_id": PROJECT_ID,
        "parcel_id": "P-0245",
        "survey_number": "125/2",
        "risk_score": 82,
        "trigger": "Civil Court Stay Order Detected (O.S. 412/2023) + 5-Way Partition Dispute",
        "reason": "Interim injunction on possession granted by Sub-Court Omalur with compensation dispute. Predicted delay: 3–5 Months.",
        "recommended_action": "Early legal verification & refer disputed compensation to LA-RA Authority under Sec 3H(4) to vacate stay.",
        "created_at_display": "2026-08-23 14:30",
        "status": "Active",
        "resolution_notes": None,
        "assigned_to": None,
    },
    {
        "id": "ALT-1088",
        "level": "CRITICAL",
        "title": "HIGH RISK ALERT: Parcel P-0556",
        "project_name": PROJECT_NAME,
        "project_id": PROJECT_ID,
        "parcel_id": "P-0556",
        "survey_number": "310/2A",
        "risk_score": 89,
        "trigger": "Stale Mutation (22 Yrs) & 7-Way Heirs Lawsuit",
        "reason": "Title unmutated since 2002; active litigation in District Munsif Court regarding Hindu Succession share. Predicted delay: 5.2 Months.",
        "recommended_action": "Special Lok Adalat camp at Omalur Taluk office for consensual award distribution.",
        "created_at_display": "2026-08-23 11:15",
        "status": "Active",
        "resolution_notes": None,
        "assigned_to": None,
    },
    {
        "id": "ALT-1081",
        "level": "HIGH",
        "title": "LITIGATION RISK ALERT: Parcel P-0312",
        "project_name": PROJECT_NAME,
        "project_id": PROJECT_ID,
        "parcel_id": "P-0312",
        "survey_number": "204/1",
        "risk_score": 78,
        "trigger": "Madras High Court Writ Petition (HR&CE Inam Land)",
        "reason": "Temple trustee challenging private patta classification. Hearing scheduled for 18-Sep-2026.",
        "recommended_action": "Convene joint district-level coordination meeting with HR&CE Commissioner.",
        "created_at_display": "2026-08-22 16:40",
        "status": "In Progress",
        "resolution_notes": None,
        "assigned_to": "Dr. Rajeshwari Sundaram, IAS",
    },
    {
        "id": "ALT-1074",
        "level": "MEDIUM",
        "title": "MUTATION LAG WARNING: Parcel P-0189",
        "project_name": PROJECT_NAME,
        "project_id": PROJECT_ID,
        "parcel_id": "P-0189",
        "survey_number": "118/4B",
        "risk_score": 48,
        "trigger": "Legal Heirship Certificate Verification Pending",
        "reason": "Primary owner deceased; award notice service delayed for outstation co-owner.",
        "recommended_action": "Deploy Special Tahsildar for on-site death certificate endorsement.",
        "created_at_display": "2026-08-21 09:20",
        "status": "Assigned",
        "resolution_notes": None,
        "assigned_to": "Spl. Tahsildar (LA) Unit-2",
    },
]


# -----------------------------------------------------------------------------
# 4 case actions — mirrors src/data/mockData.ts INITIAL_ACTIONS
# -----------------------------------------------------------------------------
CASE_ACTIONS: List[Dict[str, Any]] = [
    {
        "id": "ACT-501",
        "parcel_id": "P-0245",
        "survey_number": "125/2",
        "title": "File Petition to Vacate Civil Stay & Deposit Award in LA-RA Authority",
        "action_type": "Legal Verification",
        "assigned_officer": "Thiru. M. Senthil Kumar, DRO",
        "assigned_officer_role": "CALA / Special LA Officer",
        "priority": "CRITICAL",
        "status": "Pending",
        "due_date": "2026-08-28",
        "created_at_display": "2026-08-23 15:00",
        "completed_at": None,
        "notes": "Instruct Government Pleader Omalur to submit counter-affidavit citing Supreme Court NHAI acquisition precedence.",
        "target_delay_reduction_months": 2.7,
    },
    {
        "id": "ACT-498",
        "parcel_id": "P-0189",
        "survey_number": "118/4B",
        "title": "Special Field Verification & Heirship Endorsement Camp",
        "action_type": "Joint Mutation Camp",
        "assigned_officer": "Spl. Tahsildar (LA) Unit-2",
        "assigned_officer_role": "Field Verification Officer",
        "priority": "MEDIUM",
        "status": "In Progress",
        "due_date": "2026-09-05",
        "created_at_display": "2026-08-22 10:30",
        "completed_at": None,
        "notes": "Contact Coimbatore resident co-sharer to obtain bank mandate and indemnity bond.",
        "target_delay_reduction_months": 1.4,
    },
    {
        "id": "ACT-492",
        "parcel_id": "P-0312",
        "survey_number": "204/1",
        "title": "Collector-Level Joint Hearing with HR&CE Board",
        "action_type": "Collector Hearing",
        "assigned_officer": "Dr. Rajeshwari Sundaram, IAS",
        "assigned_officer_role": "District Collector",
        "priority": "HIGH",
        "status": "In Progress",
        "due_date": "2026-09-10",
        "created_at_display": "2026-08-21 14:00",
        "completed_at": None,
        "notes": "Evaluate Section 3H deposit structure into Temple Trust escrow account.",
        "target_delay_reduction_months": 2.7,
    },
    {
        "id": "ACT-485",
        "parcel_id": "P-0084",
        "survey_number": "44/1A",
        "title": "Boundary Geo-tagging & Handover to Construction Contractor",
        "action_type": "Field Geo-Survey",
        "assigned_officer": "Site Engineer, NHAI PIU",
        "assigned_officer_role": "Project Engineer",
        "priority": "LOW",
        "status": "Completed",
        "due_date": "2026-08-20",
        "created_at_display": "2026-08-15 09:00",
        "completed_at": "2026-08-20 17:30",
        "notes": "All 4 boundary corner stones DGPS geo-tagged and right of way fencing erected.",
        "target_delay_reduction_months": 0.2,
    },
]


# -----------------------------------------------------------------------------
# 3 audit logs — mirrors src/data/mockData.ts INITIAL_AUDIT_LOGS
# -----------------------------------------------------------------------------
AUDIT_LOGS: List[Dict[str, Any]] = [
    {
        "id": "LOG-901",
        "timestamp_display": "2026-08-23 15:10",
        "officer_id": "user-cala",
        "officer_name": "Thiru. M. Senthil Kumar, DRO",
        "role": "CALA / DRO",
        "action": "Created Case Action ACT-501 (Legal Verification)",
        "parcel_id": "P-0245",
        "survey_number": "125/2",
        "details": "Initiated legal action to vacate interim stay in O.S. 412/2023 at Sub-Court Omalur.",
    },
    {
        "id": "LOG-900",
        "timestamp_display": "2026-08-23 14:45",
        "officer_id": "user-cala",
        "officer_name": "Thiru. M. Senthil Kumar, DRO",
        "role": "CALA / DRO",
        "action": "Executed AI Delay Prediction Engine on Parcel P-0245",
        "parcel_id": "P-0245",
        "survey_number": "125/2",
        "details": "Model generated 82% Delay Probability (High Risk, 3–5 Months delay).",
    },
    {
        "id": "LOG-899",
        "timestamp_display": "2026-08-23 14:40",
        "officer_id": "user-cala",
        "officer_name": "Thiru. M. Senthil Kumar, DRO",
        "role": "CALA / DRO",
        "action": "Ran Simulated Government Data Sync (e-Courts & Bhoomi — Demo)",
        "parcel_id": "P-0245",
        "survey_number": "125/2",
        "details": "Replayed simulated court case CNR TNSL010045232023 and Patta 904 sample records. No live government connection.",
    },
]


def _upsert(session, model, record: Dict[str, Any]) -> str:
    """
    Insert `record` if its `id` doesn't exist yet; otherwise overwrite the
    existing row's fields in place. Returns 'inserted' or 'updated' for the
    caller's summary. This is what makes re-running seed.py safe: the same
    six mock-data records always land on the same six rows, never duplicates.
    """
    existing = session.get(model, record["id"])
    if existing is None:
        session.add(model(**record))
        return "inserted"
    for key, value in record.items():
        setattr(existing, key, value)
    return "updated"


def run_seed() -> Dict[str, Dict[str, int]]:
    """Creates tables if missing (belt-and-suspenders; Alembic already owns
    schema creation) and upserts every seed record. Returns a summary dict."""
    Base.metadata.create_all(bind=engine, checkfirst=True)

    summary: Dict[str, Dict[str, int]] = {}
    session = SessionLocal()
    try:
        for label, model, records in (
            ("projects", Project, PROJECTS),
            ("parcels", Parcel, PARCELS),
            ("alerts", Alert, ALERTS),
            ("case_actions", CaseAction, CASE_ACTIONS),
            ("audit_logs", AuditLog, AUDIT_LOGS),
        ):
            counts = {"inserted": 0, "updated": 0}
            for record in records:
                outcome = _upsert(session, model, record)
                counts[outcome] += 1
            summary[label] = counts
        session.commit()
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()

    # predictions: deliberately not seeded — see module docstring.
    summary["predictions"] = {"inserted": 0, "updated": 0}
    return summary


if __name__ == "__main__":
    result = run_seed()
    print("Seed complete:")
    for table, counts in result.items():
        print(f"  {table:15s} inserted={counts['inserted']:<3d} updated={counts['updated']:<3d}")
