"""add exposure engine table

Revision ID: 59b89e7f6975
Revises: ee05da00ead9
Create Date: 2026-09-15 16:46:07.273305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59b89e7f6975'
down_revision: Union[str, Sequence[str], None] = 'ee05da00ead9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exposure_assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_reference', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('parcel_id', sa.String(), nullable=True),
    sa.Column('prediction_id', sa.String(), nullable=True),
    sa.Column('primary_blocker_id', sa.String(), nullable=True),
    sa.Column('secondary_blocker_ids', sa.JSON(), nullable=False),
    sa.Column('exposure_score', sa.Float(), nullable=False),
    sa.Column('exposure_band', sa.String(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('priority_band', sa.String(), nullable=False),
    sa.Column('confidence_label', sa.String(), nullable=False),
    sa.Column('unresolved_conflict', sa.Boolean(), nullable=False),
    sa.Column('component_trace', sa.JSON(), nullable=False),
    sa.Column('recommended_action_id', sa.String(), nullable=True),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('calculation_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['primary_blocker_id'], ['blockers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommended_action_id'], ['blocker_actions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exposure_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exposure_assessments_case_reference'), ['case_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_exposure_assessments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_exposure_assessments_exposure_band'), ['exposure_band'], unique=False)
        batch_op.create_index(batch_op.f('ix_exposure_assessments_parcel_id'), ['parcel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exposure_assessments_prediction_id'), ['prediction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exposure_assessments_primary_blocker_id'), ['primary_blocker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exposure_assessments_priority_band'), ['priority_band'], unique=False)
        batch_op.create_index(batch_op.f('ix_exposure_assessments_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exposure_assessments_recommended_action_id'), ['recommended_action_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exposure_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exposure_assessments_recommended_action_id'))
        batch_op.drop_index(batch_op.f('ix_exposure_assessments_project_id'))
        batch_op.drop_index(batch_op.f('ix_exposure_assessments_priority_band'))
        batch_op.drop_index(batch_op.f('ix_exposure_assessments_primary_blocker_id'))
        batch_op.drop_index(batch_op.f('ix_exposure_assessments_prediction_id'))
        batch_op.drop_index(batch_op.f('ix_exposure_assessments_parcel_id'))
        batch_op.drop_index(batch_op.f('ix_exposure_assessments_exposure_band'))
        batch_op.drop_index(batch_op.f('ix_exposure_assessments_created_at'))
        batch_op.drop_index(batch_op.f('ix_exposure_assessments_case_reference'))

    op.drop_table('exposure_assessments')
    # ### end Alembic commands ###
