"""add statutory clock engine tables

Revision ID: 9e314c0fd8a0
Revises: e75a06af3bce
Create Date: 2026-09-14 16:25:24.070480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e314c0fd8a0'
down_revision: Union[str, Sequence[str], None] = 'e75a06af3bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('court_stay_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_reference', sa.String(), nullable=False),
    sa.Column('court', sa.String(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('affected_parcels', sa.JSON(), nullable=False),
    sa.Column('affected_stage', sa.String(), nullable=True),
    sa.Column('source_document', sa.String(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('court_stay_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_court_stay_events_case_reference'), ['case_reference'], unique=False)

    op.create_table('event_conflicts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_reference', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('competing_event_ids', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_conflicts_case_reference'), ['case_reference'], unique=False)

    op.create_table('rule_sets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('act', sa.String(), nullable=False),
    sa.Column('section_reference', sa.String(), nullable=False),
    sa.Column('jurisdiction', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('approval_status', sa.String(), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=False),
    sa.Column('source_hash', sa.String(), nullable=False),
    sa.Column('trigger_definition', sa.JSON(), nullable=False),
    sa.Column('duration_definition', sa.JSON(), nullable=True),
    sa.Column('duration_confidence', sa.String(), nullable=False),
    sa.Column('extension_definition', sa.JSON(), nullable=True),
    sa.Column('stay_definition', sa.JSON(), nullable=True),
    sa.Column('consequence_definition', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_sets_act'), ['act'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_sets_approval_status'), ['approval_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_sets_section_reference'), ['section_reference'], unique=False)

    op.create_table('extension_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_reference', sa.String(), nullable=False),
    sa.Column('rule_set_id', sa.String(), nullable=False),
    sa.Column('extension_order_id', sa.String(), nullable=True),
    sa.Column('extension_date', sa.Date(), nullable=True),
    sa.Column('authority', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source_document', sa.String(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extension_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extension_evidence_case_reference'), ['case_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_extension_evidence_rule_set_id'), ['rule_set_id'], unique=False)

    op.create_table('acquisition_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_reference', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('parcel_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('applicable_act', sa.String(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_reference', sa.String(), nullable=False),
    sa.Column('source_document_id', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supersedes_event_id', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_event_id'], ['acquisition_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('acquisition_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_acquisition_events_applicable_act'), ['applicable_act'], unique=False)
        batch_op.create_index(batch_op.f('ix_acquisition_events_case_reference'), ['case_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_acquisition_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_acquisition_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_acquisition_events_parcel_id'), ['parcel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_acquisition_events_project_id'), ['project_id'], unique=False)

    op.create_table('statutory_clocks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_reference', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('parcel_id', sa.String(), nullable=True),
    sa.Column('applicable_act', sa.String(), nullable=False),
    sa.Column('section_reference', sa.String(), nullable=False),
    sa.Column('rule_set_id', sa.String(), nullable=False),
    sa.Column('rule_set_version', sa.String(), nullable=False),
    sa.Column('trigger_event_id', sa.String(), nullable=True),
    sa.Column('trigger_date', sa.Date(), nullable=True),
    sa.Column('statutory_period', sa.String(), nullable=False),
    sa.Column('computed_deadline', sa.Date(), nullable=True),
    sa.Column('extension_status', sa.String(), nullable=False),
    sa.Column('extension_evidence_id', sa.String(), nullable=True),
    sa.Column('stay_adjustment_days', sa.Integer(), nullable=False),
    sa.Column('adjusted_deadline', sa.Date(), nullable=True),
    sa.Column('calculation_date', sa.Date(), nullable=False),
    sa.Column('days_elapsed', sa.Integer(), nullable=True),
    sa.Column('days_remaining', sa.Integer(), nullable=True),
    sa.Column('clock_status', sa.String(), nullable=False),
    sa.Column('consequence_class', sa.String(), nullable=False),
    sa.Column('calculation_basis', sa.String(), nullable=False),
    sa.Column('source_references', sa.JSON(), nullable=False),
    sa.Column('event_conflict_id', sa.String(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('calculation_version', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_conflict_id'], ['event_conflicts.id'], ),
    sa.ForeignKeyConstraint(['extension_evidence_id'], ['extension_evidence.id'], ),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.id'], ),
    sa.ForeignKeyConstraint(['trigger_event_id'], ['acquisition_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('statutory_clocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_statutory_clocks_applicable_act'), ['applicable_act'], unique=False)
        batch_op.create_index(batch_op.f('ix_statutory_clocks_case_reference'), ['case_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_statutory_clocks_clock_status'), ['clock_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_statutory_clocks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_statutory_clocks_parcel_id'), ['parcel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_statutory_clocks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_statutory_clocks_rule_set_id'), ['rule_set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_statutory_clocks_section_reference'), ['section_reference'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statutory_clocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statutory_clocks_section_reference'))
        batch_op.drop_index(batch_op.f('ix_statutory_clocks_rule_set_id'))
        batch_op.drop_index(batch_op.f('ix_statutory_clocks_project_id'))
        batch_op.drop_index(batch_op.f('ix_statutory_clocks_parcel_id'))
        batch_op.drop_index(batch_op.f('ix_statutory_clocks_created_at'))
        batch_op.drop_index(batch_op.f('ix_statutory_clocks_clock_status'))
        batch_op.drop_index(batch_op.f('ix_statutory_clocks_case_reference'))
        batch_op.drop_index(batch_op.f('ix_statutory_clocks_applicable_act'))

    op.drop_table('statutory_clocks')
    with op.batch_alter_table('acquisition_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_acquisition_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_acquisition_events_parcel_id'))
        batch_op.drop_index(batch_op.f('ix_acquisition_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_acquisition_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_acquisition_events_case_reference'))
        batch_op.drop_index(batch_op.f('ix_acquisition_events_applicable_act'))

    op.drop_table('acquisition_events')
    with op.batch_alter_table('extension_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extension_evidence_rule_set_id'))
        batch_op.drop_index(batch_op.f('ix_extension_evidence_case_reference'))

    op.drop_table('extension_evidence')
    with op.batch_alter_table('rule_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_sets_section_reference'))
        batch_op.drop_index(batch_op.f('ix_rule_sets_approval_status'))
        batch_op.drop_index(batch_op.f('ix_rule_sets_act'))

    op.drop_table('rule_sets')
    with op.batch_alter_table('event_conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_conflicts_case_reference'))

    op.drop_table('event_conflicts')
    with op.batch_alter_table('court_stay_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_court_stay_events_case_reference'))

    op.drop_table('court_stay_events')
    # ### end Alembic commands ###
