"""initial six tables

Revision ID: e75a06af3bce
Revises: 
Create Date: 2026-09-14 11:32:40.367157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e75a06af3bce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('agency', sa.String(), nullable=False),
    sa.Column('total_length_km', sa.Float(), nullable=False),
    sa.Column('project_value_crores', sa.Float(), nullable=False),
    sa.Column('total_parcels', sa.Integer(), nullable=False),
    sa.Column('acquired_parcels', sa.Integer(), nullable=False),
    sa.Column('pending_parcels', sa.Integer(), nullable=False),
    sa.Column('high_risk_parcels', sa.Integer(), nullable=False),
    sa.Column('med_risk_parcels', sa.Integer(), nullable=False),
    sa.Column('low_risk_parcels', sa.Integer(), nullable=False),
    sa.Column('predicted_delay_months', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_larr_stage', sa.String(), nullable=False),
    sa.Column('corridor_sections', sa.JSON(), nullable=False),
    sa.Column('corridor_path', sa.JSON(), nullable=False),
    sa.Column('start_point_name', sa.String(), nullable=True),
    sa.Column('end_point_name', sa.String(), nullable=True),
    sa.Column('start_lat', sa.Float(), nullable=True),
    sa.Column('start_lng', sa.Float(), nullable=True),
    sa.Column('end_lat', sa.Float(), nullable=True),
    sa.Column('end_lng', sa.Float(), nullable=True),
    sa.Column('is_custom_project', sa.Boolean(), nullable=True),
    sa.Column('project_type', sa.String(), nullable=True),
    sa.Column('planning_priorities', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parcels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('survey_number', sa.String(), nullable=False),
    sa.Column('ulpin', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=False),
    sa.Column('co_owners', sa.JSON(), nullable=False),
    sa.Column('co_owner_count', sa.Integer(), nullable=False),
    sa.Column('village', sa.String(), nullable=False),
    sa.Column('taluk', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('area_acres', sa.Float(), nullable=False),
    sa.Column('area_sq_meters', sa.Float(), nullable=False),
    sa.Column('mutation_status', sa.String(), nullable=False),
    sa.Column('last_mutation_years_ago', sa.Integer(), nullable=False),
    sa.Column('document_status', sa.String(), nullable=False),
    sa.Column('record_freshness_score', sa.Integer(), nullable=False),
    sa.Column('record_confidence', sa.String(), nullable=False),
    sa.Column('court_case', sa.Boolean(), nullable=False),
    sa.Column('court_case_status', sa.String(), nullable=False),
    sa.Column('ownership_dispute', sa.String(), nullable=False),
    sa.Column('court_record', sa.JSON(), nullable=True),
    sa.Column('revenue_record', sa.JSON(), nullable=True),
    sa.Column('gis_record', sa.JSON(), nullable=True),
    sa.Column('acquisition_status', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('notification_date', sa.String(), nullable=False),
    sa.Column('compensation_status', sa.String(), nullable=False),
    sa.Column('estimated_compensation_crores', sa.Float(), nullable=False),
    sa.Column('possession_status', sa.String(), nullable=False),
    sa.Column('delay_risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('predicted_delay_months', sa.Float(), nullable=False),
    sa.Column('predicted_delay_range', sa.String(), nullable=False),
    sa.Column('delay_confidence', sa.String(), nullable=False),
    sa.Column('top_risk_factor', sa.String(), nullable=False),
    sa.Column('ai_explanation', sa.Text(), nullable=False),
    sa.Column('shap_factors', sa.JSON(), nullable=False),
    sa.Column('risk_factors_list', sa.JSON(), nullable=False),
    sa.Column('delay_probability', sa.Float(), nullable=True),
    sa.Column('is_real_api_prediction', sa.Boolean(), nullable=True),
    sa.Column('api_error', sa.Text(), nullable=True),
    sa.Column('survival_analysis', sa.JSON(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('predicted_delay_after_intervention', sa.Float(), nullable=False),
    sa.Column('potential_reduction_months', sa.Float(), nullable=False),
    sa.Column('intervention_status', sa.String(), nullable=False),
    sa.Column('assigned_officer', sa.String(), nullable=True),
    sa.Column('assigned_due_date', sa.String(), nullable=True),
    sa.Column('field_verified', sa.Boolean(), nullable=False),
    sa.Column('field_verification_notes', sa.Text(), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=False),
    sa.Column('gps_lng', sa.Float(), nullable=False),
    sa.Column('evidence_photo_attached', sa.Boolean(), nullable=True),
    sa.Column('field_verified_at', sa.String(), nullable=True),
    sa.Column('map_coordinates', sa.JSON(), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lng', sa.Float(), nullable=False),
    sa.Column('last_synced_at', sa.String(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parcels_project_id'), ['project_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=False),
    sa.Column('survey_number', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('created_at_display', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_parcel_id'), ['parcel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_project_id'), ['project_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp_display', sa.String(), nullable=False),
    sa.Column('officer_id', sa.String(), nullable=False),
    sa.Column('officer_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=True),
    sa.Column('survey_number', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_parcel_id'), ['parcel_id'], unique=False)

    op.create_table('case_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=False),
    sa.Column('survey_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('assigned_officer', sa.String(), nullable=False),
    sa.Column('assigned_officer_role', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('due_date', sa.String(), nullable=False),
    sa.Column('created_at_display', sa.String(), nullable=False),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('target_delay_reduction_months', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_actions_parcel_id'), ['parcel_id'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('generated_at', sa.String(), nullable=False),
    sa.Column('is_real_api_prediction', sa.Boolean(), nullable=False),
    sa.Column('prediction_mode', sa.String(), nullable=True),
    sa.Column('api_error', sa.Text(), nullable=True),
    sa.Column('model_input', sa.JSON(), nullable=False),
    sa.Column('sample_coverage', sa.JSON(), nullable=True),
    sa.Column('input_diagnostics', sa.JSON(), nullable=True),
    sa.Column('aggregation_notes', sa.JSON(), nullable=False),
    sa.Column('delay_probability', sa.Float(), nullable=False),
    sa.Column('delay_risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('predicted_delay_months', sa.Float(), nullable=True),
    sa.Column('predicted_delay_range', sa.String(), nullable=False),
    sa.Column('top_risk_factor', sa.String(), nullable=False),
    sa.Column('ai_explanation', sa.Text(), nullable=False),
    sa.Column('shap_factors', sa.JSON(), nullable=False),
    sa.Column('survival_analysis', sa.JSON(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_parcel_id'), ['parcel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_project_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_parcel_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_created_at'))

    op.drop_table('predictions')
    with op.batch_alter_table('case_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_actions_parcel_id'))

    op.drop_table('case_actions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_parcel_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_project_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_parcel_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parcels_project_id'))

    op.drop_table('parcels')
    op.drop_table('projects')
    # ### end Alembic commands ###
