"""add blocker engine tables

Revision ID: ee05da00ead9
Revises: 9e314c0fd8a0
Create Date: 2026-09-14 21:11:38.695107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee05da00ead9'
down_revision: Union[str, Sequence[str], None] = '9e314c0fd8a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('evaluation_run_id', sa.String(), nullable=False),
    sa.Column('case_reference', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('parcel_id', sa.String(), nullable=True),
    sa.Column('blocker_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('owner_role', sa.String(), nullable=False),
    sa.Column('responsible_authority', sa.String(), nullable=False),
    sa.Column('affects_clock', sa.Boolean(), nullable=False),
    sa.Column('affected_clock_ids', sa.JSON(), nullable=False),
    sa.Column('affects_possession', sa.Boolean(), nullable=False),
    sa.Column('affects_project', sa.Boolean(), nullable=False),
    sa.Column('downstream_extent', sa.JSON(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('ranking_basis', sa.JSON(), nullable=False),
    sa.Column('resolution_status', sa.String(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=False),
    sa.Column('resolution_evidence_refs', sa.JSON(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('calculation_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blockers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blockers_blocker_type'), ['blocker_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockers_case_reference'), ['case_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockers_evaluation_run_id'), ['evaluation_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockers_is_primary'), ['is_primary'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockers_parcel_id'), ['parcel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockers_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blockers_status'), ['status'], unique=False)

    op.create_table('blocker_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('blocker_id', sa.String(), nullable=True),
    sa.Column('owner_role', sa.String(), nullable=False),
    sa.Column('authority', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('precedent_refs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blocker_id'], ['blockers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blocker_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocker_actions_blocker_id'), ['blocker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocker_actions_created_at'), ['created_at'], unique=False)

    op.create_table('blocker_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('blocker_id', sa.String(), nullable=True),
    sa.Column('evidence_type', sa.String(), nullable=False),
    sa.Column('source_ref_type', sa.String(), nullable=False),
    sa.Column('source_ref_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('relation', sa.String(), nullable=False),
    sa.Column('observed_at', sa.Date(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blocker_id'], ['blockers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blocker_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocker_evidence_blocker_id'), ['blocker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocker_evidence_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocker_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocker_evidence_created_at'))
        batch_op.drop_index(batch_op.f('ix_blocker_evidence_blocker_id'))

    op.drop_table('blocker_evidence')
    with op.batch_alter_table('blocker_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocker_actions_created_at'))
        batch_op.drop_index(batch_op.f('ix_blocker_actions_blocker_id'))

    op.drop_table('blocker_actions')
    with op.batch_alter_table('blockers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blockers_status'))
        batch_op.drop_index(batch_op.f('ix_blockers_project_id'))
        batch_op.drop_index(batch_op.f('ix_blockers_parcel_id'))
        batch_op.drop_index(batch_op.f('ix_blockers_is_primary'))
        batch_op.drop_index(batch_op.f('ix_blockers_evaluation_run_id'))
        batch_op.drop_index(batch_op.f('ix_blockers_created_at'))
        batch_op.drop_index(batch_op.f('ix_blockers_case_reference'))
        batch_op.drop_index(batch_op.f('ix_blockers_blocker_type'))

    op.drop_table('blockers')
    # ### end Alembic commands ###
